logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config


[X友交流汇]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
arch = "arm64-v8a"
build-mode = "both"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
build-mode = "both"
